#-*- coding: utf-8 -*-
#######################################################
# 
# splash.py
# Python implementation of the Class Splash
# Generated by Enterprise Architect
# Created on:      30-mai-2011 14:15:33
# Original author: Wander Jardim
# 
#######################################################

from graphics import Image
import util

class Splash:
    
    def __init__ (self):
        self.largura_tela, self.altura_tela = util.getTamanho_tela()
        self.fundoSplash=util.cria_imagem('splash.png')
        


    def desenha_splash(self, canvas):
        tela_splash = Image.new((self.largura_tela, self.altura_tela))
        mascaraSplash = Image.new((self.largura_tela, self.altura_tela), 'L')
        for i in range(0,26):
            fond=0
            texte=(10*i)
            mascaraSplash.clear((texte,texte,texte))
            tela_splash.clear((fond,fond,fond))
            tela_splash.blit(self.fundoSplash,mask=mascaraSplash)
            canvas.blit(tela_splash) # mostra a imagem na tela