#######################################################
# 
# clienteWiFi.py
# Python implementation of the Class ClienteWiFi
# Generated by Enterprise Architect
# Created on:      26-jul-2011 17:29:19
# Original author: Wander Jardim
# 
#######################################################


class ClienteWiFi:
    def __init__(self):
        pass