# -*- coding: utf-8 -*-
#######################################################
# 
# jogo.py
# Python implementation of the Class Jogo
# Generated by Enterprise Architect
# Created on:      31-mai-2011 15:43:56
# Original author: Wander Jardim
# 
#######################################################

import appuifw
import sysinfo
from graphics import Image
import traceback
import key_codes
import e32

import clienteBT
from constantes import *
import util
import json

class Jogo:
    def __init__(self, conexao):
        try: 
            self.render=0
            self.file_erro = 'E:\\Python\\Meu_error2.log'
            self.conexao = conexao
            self.largura_tela, self.altura_tela = util.getTamanho_tela()
            self.telajogo = Image.new((self.largura_tela,self.altura_tela))
            self.espacoCartas = None
            self.cartas = None
            self.matrizCartas = util.cria_imagem('matrizCartas.png')
            self.matrizBotoes = util.cria_imagem('BotoesIncrementos.png')
            self.espacoVez = Image.new((400,30)) #espacoCartas.size)
            self.espacoPontos = Image.new((104,30))
            self.espacoPontosNos = Image.new((40,25))
            self.espacoPontosEles = Image.new((40,25))
            self.euPediTruco = False
            
            
            
            self.canvas = appuifw.Canvas(event_callback = self.handle_event,
                                         redraw_callback = self.handle_redraw)
            appuifw.app.body = self.canvas
            #appuifw.app.menu = [(u"Descartar", self.descartar), (u"Envia qq coisa", self.enviaqqcoisa), (u'Envia um texto', self.enviatxtPerso) ]
            
            self.render=1
            
            self.fundoMesa = util.cria_imagem('fundoMesa.png')
            
            
            #Botão Sair
            self.quit = appuifw.app.exit_key_handler
            rect_bot_sair = ((609,335),(625,351)) # ((5, 5),(25, 25)) 
            self.fundoMesa.rectangle(rect_bot_sair, outline=RGB_BLUE, width=1)
            self.canvas.bind(key_codes.EButton1Up, self.quit, rect_bot_sair)
            
            espacoCartas = util.cria_imagem('espacoCartas.png')
            self.espacoCartas = Image.new(espacoCartas.size) #espacoCartas.size)
            self.maskCartas = Image.new(espacoCartas.size, 'L') #tons de cinza 8-bits
            self.maskCartas.blit(espacoCartas)
            
            espacoBotoesIncremento  = util.cria_imagem('espacoBotoesIncremento.png')
            self.espacoBotoesIncremento = Image.new(espacoBotoesIncremento.size) 
            self.maskBotoes = Image.new(espacoBotoesIncremento.size, 'L') #tons de cinza 8-bits
            self.maskCartas.blit(espacoBotoesIncremento)
            
            #espacoInfos = util.cria_imagem('espacoInfos.png')
            #self.espacoInfos = Image.new(espacoInfos.size) #espacoCartas.size)
            
            #self.maskInfos = Image.new(espacoInfos.size, 'L') #tons de cinza 8-bits
            #self.maskInfos.blit(espacoInfos)
            
            
            self.posBolinha = 3
            self.bolaVerde = util.cria_imagem('BolinhaVerde.png')
            self.bolaVermelha = util.cria_imagem('BolinhaVermelha.png')
            mascaraBolas = util.cria_imagem('MascaraBolinha.png')
            self.maskbolas = Image.new(mascaraBolas.size, 'L')
            self.maskbolas.blit(mascaraBolas)
            
            self.telajogo.blit(self.fundoMesa)
            # mostra a imagem na tela
            self.canvas.blit(self.telajogo)
    
            #Botão Descartar
            rect_botao_descartar = ((512,160),(630,200)) #((303,64),(452,114)) # 
            self.fundoMesa.rectangle(rect_botao_descartar, outline=RGB_BLUE, width=1)
            self.canvas.bind(key_codes.EButton1Down, self.descartar, rect_botao_descartar)
            
            #Botão Truco
            rect_botao_truco = ((513,263),(630,301)) #((303,64),(452,114)) # 
            self.fundoMesa.rectangle(rect_botao_truco, outline=RGB_BLUE, width=1)
            self.canvas.bind(key_codes.EButton1Down, self.pedirTuco, rect_botao_truco)
            
            self.espacoPontosNos.clear(RGB_VERDE)
            self.espacoPontosNos.text((2, 23), u"0", fill = RGB_BLACK,font=(u'Nokia Hindi S60',30,appuifw.STYLE_BOLD))
            self.espacoPontosEles.clear(RGB_VERDE)
            self.espacoPontosEles.text((2, 23), u"0", fill = RGB_BLACK,font=(u'Nokia Hindi S60',30,appuifw.STYLE_BOLD))
                                
            
        except Exception, erro:
            msgErro = "Erro no INIT: " + str(erro) + "\n"
            self.log(msgErro)
            raise
        
    
    def pedirTuco(self, rect):
        self.conexao.envia_comando(json.write({'truco':'pedido'}))
        self.euPediTruco = True
        
        

    def enviatxtPerso(self):
        texto = appuifw.query("Digite o texto", 'text')
        textoEnviar = eval(texto)
        self.conexao.envia_comando(json.write(textoEnviar))

    def log(self, log):
        open(self.file_erro, 'a').write(log)


    def cria_cartas(self,cartas_recebidas):
        #Criando as cartas:
        self.cartas = []
        for i in range(len(cartas_recebidas)):
            self.cartas.append(Carta(posCartas[i], dictCartas[cartas_recebidas[i]], posCartasSelec[i], cartas_recebidas[i]))

    def desenhaBotoesIncremento(self, nomeBotao):
        
        self.canvas.blit(self.matrizBotoes, target=(0,0), source=listBotoes[nomeBotao])
    
    
            
    def desenhaCartas(self):
        #mask = util.cria_imagem('mascaraCartas.png')
        #self.maskCarta = Image.new(mask.size, 'L') #tons de cinza 8-bits
        #self.maskCarta.blit(mask) 
        for carta in self.cartas:
            self.carregaCarta(carta)
            self.canvas.blit(carta.imagem, target = carta.posicao_mesa)
            self.canvas.bind(key_codes.EButton1Up, self.seleciona_carta, carta.rect)
            self.canvas.bind(key_codes.EButton1Down, self.deseleciona_carta, carta.rect) 

    def carregaCarta(self, carta):
        carta.imagem.blit(self.matrizCartas, target=(0, 0), source=carta.source)


    def loop_jogo(self):
        try: 
            if self.conexao.esta_conectado():
                pos = 95
                while True:
                    
                    self.data = json.read(self.conexao.recebe_comando())
                    
                    
                    print self.data
                    self.log("recebido: %s \n" % self.data)
                    if not self.data :
                        break
                    else:
                        if 'cartas' in self.data: #startswith('cartas'):
                            #self.cartas = data['cartas']
                            #print "dados recebido (inicio cartas): %s" % data
                            #self.log("dados recebido (inicio cartas): %s" % data)
                            #dadosRecebidos = data.split(':')
                            
                            self.cartas_recebidas = self.data['cartas'] #dadosRecebidos[1].split('/')
                            self.conexao.envia_comando(json.write({'OK':'Cartas Recebidas'}))
                            self.cria_cartas(self.cartas_recebidas)
                            self.desenhaCartas()
                        
                        
                        
                        elif 'truco' in self.data:
                            if self.data['truco'].startswith(":"):
                                nomeJogadorPediuTruco = self.data['truco'].split(':')[1]
                                self.informaPedidoTruco(nomeJogadorPediuTruco)
                                self.conexao.envia_comando(json.write({'OK':'Pedido Informado'}))
                                
                            elif self.data['truco'] == 'aceita?':
                                resp = appuifw.query(u"O Jogador %s pediu Truco. Aceita?" % nomeJogadorPediuTruco, 'query')
                                if resp:
                                    respTruco = 'sim'
                                else:
                                    respTruco = 'nao'
                                    
                                self.conexao.envia_comando(respTruco)
                                e32.ao_sleep(1)
                                
                                if respTruco == 'sim':
                                    #desenhar o botão Meio-Pau
                                    pass
                                    
                                
                            
                            elif self.data['truco'].startswith('aceitou') :
                                nomeJogadorAceitouTruco = self.data['truco'].split(':')[1]
                                
                                self.desabiltaBotaoTruco()
                                
                                if self.euPediTruco:
                                    #self.mostraInfos('O Jogador %s aceitou o Truco. Jogue sua carta.' % nomeJogadorAceitouTruco)
                                    appuifw.note(u"O Jogador %s aceitou o Truco. Jogue sua carta." % nomeJogadorAceitouTruco, 'info')
                                else:
                                    self.mostraInfos('O Jogador %s aceitou o Truco' % nomeJogadorAceitouTruco)
                                    
                                self.conexao.envia_comando(json.write({'OK':'O Jogador %s aceitou o Truco' % nomeJogadorAceitouTruco}))
                                
                            elif self.data['truco'].startswith('recusou') :
                                pass
                            
                            
                            elif self.data['truco'] == '':
                                pass
                        
                        
                        elif 'fim-mao' in self.data:
                            print "Recebi comando de fim de Mao"
                            if self.data['fim-mao'][0] == 'ganhou':
                                self.espacoPontosNos.clear(RGB_VERDE)
                                self.espacoPontosNos.text((2, 23), u"%s" % self.data['fim-mao'][1], fill = RGB_BLACK,font=(u'Nokia Hindi S60',30,appuifw.STYLE_BOLD))
                                self.canvas.blit(self.espacoPontosNos, target = (407,97))
                            elif self.data['fim-mao'][0] == 'perdeu':
                                self.espacoPontosEles.clear(RGB_VERDE)
                                self.espacoPontosEles.text((2, 23), u"%s" % self.data['fim-mao'][1], fill = RGB_BLACK,font=(u'Nokia Hindi S60',30,appuifw.STYLE_BOLD))
                                
                                
                            #self.telajogo.text((10, pos), u"recv >> %s" % data, fill = RGB_BLACK,font=(u'Nokia Hindi S60',20,appuifw.STYLE_BOLD))
                            #self.canvas.blit(self.telajogo)
                            self.handle_redraw()
                            self.limpaCartasMao()
                            self.euPediTruco = False
                            self.conexao.envia_comando(json.write({'OK':'Fim Mao'}))
                            
                            
                        
                        elif 'fim-partida' in self.data:
                            self.informaFimPartida()
                                
                                
                            
                            
                            
                        elif 'vez' in self.data:
                            self.mostraVez(self.data['vez'])
                        
                        elif 'pontos' in self.data:
                            self.mostraPontos(self.data['pontos'])
                        
                        
                        
                        elif self.data == 1:
                            pass   
                        
                        
                        else:
                            #self.mostraVez(data)
                            print "<< %s >>" % str(self.data) 
                            
                            
                            #self.telajogo.text((10, pos), u"recv >> %s" % data, fill = RGB_BLACK,font=(u'Nokia Hindi S60',20,appuifw.STYLE_BOLD))
                            #self.canvas.blit(self.telajogo)
                            #self.handle_redraw()
                        pos += 15
                        
        except Exception, erro:
            msgErro = "Erro do loop_jogo: " + str(erro) + "\n"
            print msgErro
            self.log(msgErro)
            raise



    def desabiltaBotaoTruco(self):
        #incluir código para desabilitar o botão de truco
        pass

    def mostraPontos(self, quem):
        
        #self.espacoPontos.clear(COR_FD_INFOS)
        
        if quem ==  'nosso':
            self.espacoPontos.blit(self.bolaVerde, target = (self.posBolinha,2), mask=self.maskbolas)
        elif quem == 'outros':
            self.espacoPontos.blit(self.bolaVermelha, target = (self.posBolinha,2), mask=self.maskbolas)
        elif quem == 'cango':
            pass
            #self.espacoPontos.blit(self.bolaAmarela, target = (self.posBolinha,2), mask=self.maskbolas)
        
        self.handle_redraw()
        self.posBolinha += 35

        
        

    def mostraVez(self, nome):
        self.espacoVez.clear(COR_FD_INFOS)
        self.espacoVez.text((5,25), u">> %s" % nome, fill = RGB_BLUE,font=(u'Nokia Hindi S60',20,appuifw.STYLE_BOLD))
        #self.canvas.blit(self.espacoVez, target = (40,40))
        self.handle_redraw()

    def mostraInfos(self, info):
        
        self.espacoVez.clear(COR_FD_INFOS)
        self.espacoVez.text((5,25), u"%s" % info, fill = RGB_BLACK,font=(u'Nokia Hindi S60',20,appuifw.STYLE_BOLD))
        #self.canvas.blit(self.telajogo)
        self.handle_redraw()            
        
    

    def informaPedidoTruco(self, nome):
        
        self.espacoVez.clear(COR_FD_INFOS)
        self.espacoVez.text((5,25), u"O Jogador %s pediu Truco " % nome, fill = RGB_BLACK,font=(u'Nokia Hindi S60',20,appuifw.STYLE_BOLD))
        #self.canvas.blit(self.telajogo)
        self.handle_redraw()
        


    def limpaCartasMao(self):
        intervalo = len(self.cartas)
        for carta in range(intervalo):
            self.cartas.pop()

        self.espacoCartas.clear(0)
        self.espacoPontos.clear(COR_FD_INFOS)
        self.posBolinha = 3
        #self.telajogo.text((10, 20), u"FIM DA MÃO", fill = RGB_BLACK,font=(u'Nokia Hindi S60',20,appuifw.STYLE_BOLD))
        self.canvas.blit(self.telajogo)
        self.handle_redraw()
    
    def informaFimPartida(self):
        pass


    def tocou_na_carta(self, pos, carta):
        if  pos[0] >= carta[0][0] and pos[0] <  carta[1][0]\
        and pos[1] >= carta[0][1] and pos[1] <  carta[1][1]:
            return True
        return False
        
    
    def deseleciona_carta(self, pos):
        for carta in self.cartas:
            if self.tocou_na_carta(pos, carta.rect):
                self.espacoCartas.clear(0)
                self.espacoCartas.rectangle(carta.pos_marca_selecao, outline=RGB_RED, width=3, fill=RGB_RED)
                self.canvas.blit(self.espacoCartas, target = POS_ESPAC_CARTAS, mask=self.maskCartas)
            else:
                carta.selecionada = False
        
    def seleciona_carta(self, pos):
        ''' Seleciona carta '''
        for i in range(len(self.cartas)):
            if self.tocou_na_carta(pos, self.cartas[i].rect):
                self.espacoCartas.clear(0)
                
                self.espacoCartas.rectangle(self.cartas[i].pos_marca_selecao, outline=RGB_BLUE, width=3, fill=RGB_BLUE)
                self.canvas.blit(self.espacoCartas, target = POS_ESPAC_CARTAS, mask=self.maskCartas)
                self.cartas[i].selecionada = True
                break

    def descartar(self, pos=None):
        print "To descartando!!!"
        for carta in self.cartas:
            if carta.selecionada == True:
                print "Descartei: %s" % carta.valor
                
                self.conexao.envia_comando(json.write({"carta":carta.valor}))
                self.cartas.remove(carta)
                print "Tamanho de Cartas: %s" % len(self.cartas)
                self.espacoCartas.clear(0)
                self.handle_redraw()



    def handle_event(self, evento):
        #print evento
        pass
        


    def handle_redraw(self, rect=None):
        if self.telajogo:
            self.canvas.blit(self.telajogo)
            if self.cartas:
                self.desenhaCartas()
                
        if self.espacoCartas:
            self.canvas.blit(self.espacoCartas, target = POS_ESPAC_CARTAS, mask=self.maskCartas)
        if self.espacoVez:
            self.canvas.blit(self.espacoVez, target = (22,10))
        if self.espacoPontos:
            self.canvas.blit(self.espacoPontos, target = (22,58))
        if self.espacoPontosEles:
            self.canvas.blit(self.espacoPontosEles, target = (365,97))
        if self.espacoPontosNos:
            self.canvas.blit(self.espacoPontosNos, target = (407,97))

    """
    def event_redraw(self, other):
        if self.render == 0:
            self.canvas.clear()
            self.telajogo.clear((15,126,0))
            self.canvas.blit(self.telajogo)
    """




class Carta(object):
    def __init__(self, pos_mesa, source, pos_marca_selecao, valor):
        self.posicao_mesa = pos_mesa
        self.rect = (self.posicao_mesa, (self.posicao_mesa[0]+LARGU_CARTA, self.posicao_mesa[1]+ALTUR_CARTA))
        self.source = source
        self.pos_marca_selecao = pos_marca_selecao
        self.imagem = Image.new((LARGU_CARTA,ALTUR_CARTA))
        self.valor = valor
        self.selecionada = False
