#######################################################
# 
# carta.py
# Python implementation of the Class Carta
# Generated by Enterprise Architect
# Created on:      29-jul-2011 20:35:31
# Original author: Wander Jardim
# 
#######################################################


class Carta(object):
    __valores = []
    __manilhas = []
    __naipes = []
    valorJogo = ''
    valorPadrao = ''
    valorCarta = ''
    __indice_naipe = ''
    naipe = ''
    valorBT = ''
    nomeCartaPadrao = ''
    ehmanilha = False
    imagem = None

    def __init__(self, valor, naipe):
        self.__valores = [None, '4', '5', '6', '7', 'Dama', 'Valete', 'Rei', 'As', '2', '3', 'Pica Fumo', 'Espadilha', 'Escopeta', 'Zap']
        self.__manilhas = ['Pica Fumo', 'Espadilha', 'Escopeta', 'Zap']
        self.__naipes = ['Ouros','Espadas', 'Copas', 'Paus']
        self.__dir_imagens = "data/imagens/"
        self.valorJogo = valor
        self.valorPadrao = valor
        self.valorCarta = self.__valores[self.valorJogo]
        self.__indice_naipe = naipe
        self.naipe = self.__naipes[naipe]
        self.valorBT = "%s%s" % (self.valorCarta[0].isdigit() and self.valorCarta[0] or self.valorCarta[0].lower(), self.naipe[0].lower())
        self.nomeCartaPadrao = "%s de %s" % (self.__valores[self.valorPadrao], self.naipe)
        self.ehmanilha = False
        self.imagem = cocos.sprite.Sprite(self.__dir_imagens + self.montaNomeArq())
        
    def __repr__(self):
        if self.ehmanilha:
            return '%s' % self.__valores[self.valorJogo]
        else:
            return '%s de %s'%(self.__valores[self.valorJogo], self.__naipes[self.__indice_naipe])

    def montaNomeArq(self):
        return '%s-%s.gif'%(self.__valores[self.valorJogo], self.__naipes[self.__indice_naipe])