#######################################################
# 
# equipe.py
# Python implementation of the Class Equipe
# Generated by Enterprise Architect
# Created on:      29-jul-2011 22:20:03
# Original author: Wander Jardim
# 
#######################################################


class Equipe(object):
    def __init__(self, jogadores):
        self.jogadores = jogadores
        self.pontos = 0
        self.pontosMao = 0
    
    def __repr__(self):
        return '%s e %s' % (self.jogadores[0].nome, self.jogadores[1].nome)
    
    def setPontos(self, pontos):
        self.pontos += pontos
    
    def getPontos(self):
        return self.pontos
    
    def ehDaEquipe(self, jogadorE):
        for jogador in self.jogadores:
            if jogadorE is jogador:
                return True
        return False