#######################################################
# 
# mesa.py
# Python implementation of the Class Mesa
# Generated by Enterprise Architect
# Created on:      29-jul-2011 22:15:28
# Original author: Wander Jardim
# 
#######################################################


class Mesa(object):
    def __init__(self, jogadores, baralho):
        pass

    def compararCartas(self, cartas):
        pass

    def defineManilhas(self, baralho):
        pass

    def definir1aOrdemJogadores(self):
        pass

    def definirEquipes(self):
        pass

    def definirOrdemJogadores(self, novaMao):
        pass

    def distrubuirCartas(self):
        """self.equipe = 1
        """
        pass

    def limpar(self):
        pass

    def zeraManilhas(self, baralho):
        pass