#######################################################
# 
# clienteGPRS.py
# Python implementation of the Class ClienteGPRS
# Generated by Enterprise Architect
# Created on:      26-jul-2011 17:29:31
# Original author: Wander Jardim
# 
#######################################################


class ClienteGPRS:
    def __init__(self):
        pass