#######################################################
# 
# telaCreditos.py
# Python implementation of the Class TelaCreditos
# Generated by Enterprise Architect
# Created on:      26-jul-2011 20:25:51
# Original author: Wander Jardim
# 
#######################################################


class TelaCreditos( Menu ):
    def __init__(self, name = 'Voltar'):
        super( BackMenu, self).__init__() 
        items = []

        items.append( MenuItem(name, self.on_back) )

        self.create_menu( items)
        
        # Spacing
        pos = 0
        for menuItem in items:
            menuItem.y -= 300
            pos += 1
        
    def on_back(self):
        director.scene.end()
        
    def on_quit(self):
        # called by esc
        director.scene.end()


def get_scene():
    scene = Scene(BGLayer("menu"), BackMenu() )
    return scene